version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - 'node_modules_docker:/app/node_modules'

  e2e-chrome:
    image: "cypress/included:6.2.1"
    # container_name: cypress
    # "cypress/included" images have entrypoint set to globally installed cypress
    # so the command can simply add any arguments
    command: "--browser chrome"
    volumes:
      - .:/e2e
    working_dir: /e2e

volumes:
  node_modules_docker: